### ISSUE TITLE
Datentypen & Funktionen für 4×4-Matrizen & Vektoren

### ISSUE THREAD

**Issue by LinusParbel** [Sebbsen/CG1-Project#2]
- [x] Matrix-Multiplikation
- [x] Multiplikation mit Vektor
- [x] Identitätsmatrix
- [x] Translationsmatrix
- [x] Rotationsmatrix (jeweils eine pro Axis)
- [x] Skalierungsmatrix
- [x] Translations-Funktion
- [x] Rotations-Funktion (1 oder 3?)
- [x] Skalierungs-Funktion
- [x] Matrix-Inverse
- [x] Matrix-Transponiert
- [x] Vektor-Subtraktion
- [x] Vektor-Länge
- [x] Vektor-Multiplikation mit Skalar
- [x] Skalarprodukt
- [x] Kreuzprodukt

**Comment by akazumiii** [comment]
Mach ich alles pog pog
