### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by LinusParbel** [Sebbsen/CG1-Project#3]
„Schreibt eine separate Testseite, mit der alle Matrixfunktionen gründlich getestet werden.
Beachtet dabei auch mögliche Sonderfälle (z. B. dass zwei Parameter auf dieselben Arrays
verweisen). Auf der Seite solle das Ergebnis von jedem Test (Testname, „OK“/„Nicht
OK“) angezeigt werden.“

**Comment by akazumiii** [comment]
Ja das mach ich auch pog pog pog
