### ISSUE TITLE
Spiegelung der Umgebungstextur auf einigen Objekten

### ISSUE THREAD

**Issue by LinusParbel** [Sebbsen/CG1-Project#9]

**Comment by LinusParbel** [comment]
Einige Warnungen aus der Konsole sollten wir vielleicht noch beheben:

- WebGL warning: drawElementsInstanced: Tex image TEXTURE_CUBE_MAP_POSITIVE_X level 0 is incurring lazy initialization. 
- WebGL warning: drawElementsInstanced: TEXTURE_CUBE_MAP at unit 0 is incomplete: Bad mipmap dimension or format.

**Comment by Sebbsen** [comment]
use Chrome
